"""
Structured comparison data for all GUI frameworks.
Contains metrics, features, and detailed information for comparison.
"""

# Extended comparison matrix data
FRAMEWORK_DATA = {
    "Standard Tkinter": {
        "tech": "Tcl/Tk",
        "license": "PSF/BSD",
        "use_case": "Simple tools, Prototyping",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Easy",
        "python_version": "3.8+",
        "install_difficulty": "Easy",
        "community": "High",
        "performance": "Medium",
        "documentation": "Good",
        "category": "Standard & Modern",
        "github_stars": "N/A (Built-in)",
        "last_update": "2024"
    },
    "CustomTkinter": {
        "tech": "Tkinter++",
        "license": "MIT",
        "use_case": "Modern UI with Tkinter ease",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Easy",
        "python_version": "3.8+",
        "install_difficulty": "Easy",
        "community": "Medium",
        "performance": "Medium",
        "documentation": "Good",
        "category": "Standard & Modern",
        "github_stars": "12k+",
        "last_update": "2024"
    },
    "PySide6": {
        "tech": "Qt (Official)",
        "license": "LGPL",
        "use_case": "Commercial Qt apps",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Medium",
        "python_version": "3.6+",
        "install_difficulty": "Medium",
        "community": "High",
        "performance": "High",
        "documentation": "Excellent",
        "category": "Standard & Modern",
        "github_stars": "2k+",
        "last_update": "2024"
    },
    "PyQt6": {
        "tech": "Qt",
        "license": "GPL/Comm",
        "use_case": "Professional Desktop",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Medium",
        "python_version": "3.6+",
        "install_difficulty": "Medium",
        "community": "High",
        "performance": "High",
        "documentation": "Excellent",
        "category": "Standard & Modern",
        "github_stars": "N/A",
        "last_update": "2024"
    },
    "wxPython": {
        "tech": "wxWidgets",
        "license": "LGPL",
        "use_case": "Native look & feel",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Medium",
        "python_version": "3.6+",
        "install_difficulty": "Medium",
        "community": "Medium",
        "performance": "High",
        "documentation": "Good",
        "category": "Standard & Modern",
        "github_stars": "2k+",
        "last_update": "2024"
    },
    "Kivy": {
        "tech": "OpenGL",
        "license": "MIT",
        "use_case": "Touch, Multi-platform",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Medium",
        "python_version": "3.7+",
        "install_difficulty": "Medium",
        "community": "High",
        "performance": "High",
        "documentation": "Good",
        "category": "Standard & Modern",
        "github_stars": "16k+",
        "last_update": "2024"
    },
    "PySimpleGUI": {
        "tech": "Wrapper",
        "license": "LGPL/Comm",
        "use_case": "Rapid Prototypes",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Easy",
        "python_version": "3.4+",
        "install_difficulty": "Easy",
        "community": "High",
        "performance": "Medium",
        "documentation": "Excellent",
        "category": "Standard & Modern",
        "github_stars": "12k+",
        "last_update": "2024"
    },
    "Dear PyGui": {
        "tech": "ImGui/GPU",
        "license": "MIT",
        "use_case": "Performance, Vision",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Medium",
        "python_version": "3.7+",
        "install_difficulty": "Medium",
        "community": "Medium",
        "performance": "High",
        "documentation": "Good",
        "category": "Standard & Modern",
        "github_stars": "20k+",
        "last_update": "2024"
    },
    "Flet": {
        "tech": "Flutter",
        "license": "Apache 2",
        "use_case": "Cross-platform consistency",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Easy",
        "python_version": "3.7+",
        "install_difficulty": "Easy",
        "community": "Medium",
        "performance": "High",
        "documentation": "Good",
        "category": "Web-Based",
        "github_stars": "8k+",
        "last_update": "2024"
    },
    "NiceGUI": {
        "tech": "FastAPI/Vue",
        "license": "MIT",
        "use_case": "Modern Dashboards",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Easy",
        "python_version": "3.8+",
        "install_difficulty": "Easy",
        "community": "Medium",
        "performance": "Medium",
        "documentation": "Good",
        "category": "Web-Based",
        "github_stars": "5k+",
        "last_update": "2024"
    },
    "PyWebView": {
        "tech": "Browser",
        "license": "BSD",
        "use_case": "Embedded HTML wrappers",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Easy",
        "python_version": "3.6+",
        "install_difficulty": "Easy",
        "community": "Medium",
        "performance": "Medium",
        "documentation": "Basic",
        "category": "Web-Based",
        "github_stars": "4k+",
        "last_update": "2024"
    },
    "Eel": {
        "tech": "Chrome/WS",
        "license": "MIT",
        "use_case": "Web-frontends for Python",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Easy",
        "python_version": "3.5+",
        "install_difficulty": "Easy",
        "community": "Medium",
        "performance": "Medium",
        "documentation": "Basic",
        "category": "Web-Based",
        "github_stars": "6k+",
        "last_update": "2024"
    },
    "Flexx": {
        "tech": "Web Stack",
        "license": "BSD",
        "use_case": "Hybrid Web/Desktop",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Medium",
        "python_version": "3.6+",
        "install_difficulty": "Medium",
        "community": "Low",
        "performance": "Medium",
        "documentation": "Basic",
        "category": "Web-Based",
        "github_stars": "1k+",
        "last_update": "2024"
    },
    "Gooey": {
        "tech": "Tkinter",
        "license": "MIT",
        "use_case": "CLI to GUI conversion",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Easy",
        "python_version": "3.6+",
        "install_difficulty": "Easy",
        "community": "Medium",
        "performance": "Medium",
        "documentation": "Good",
        "category": "Specialized",
        "github_stars": "11k+",
        "last_update": "2024"
    },
    "Toga": {
        "tech": "Native",
        "license": "BSD",
        "use_case": "Native Mobile/Desktop",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Medium",
        "python_version": "3.7+",
        "install_difficulty": "Complex",
        "community": "Medium",
        "performance": "High",
        "documentation": "Good",
        "category": "Specialized",
        "github_stars": "1k+",
        "last_update": "2024"
    },
    "appJar": {
        "tech": "Tkinter",
        "license": "Apache 2",
        "use_case": "Educational purposes",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Easy",
        "python_version": "3.6+",
        "install_difficulty": "Easy",
        "community": "Low",
        "performance": "Medium",
        "documentation": "Good",
        "category": "Specialized",
        "github_stars": "500+",
        "last_update": "2024"
    },
    "PyGUI": {
        "tech": "Native",
        "license": "MIT",
        "use_case": "Lightweight Wrapper",
        "platforms": {"windows": False, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Medium",
        "python_version": "3.5+",
        "install_difficulty": "Complex",
        "community": "Low",
        "performance": "Medium",
        "documentation": "Basic",
        "category": "Legacy / Specialized Mockups",
        "github_stars": "200+",
        "last_update": "2024"
    },
    "PyForms": {
        "tech": ".NET/Qt",
        "license": "MIT",
        "use_case": "Windows-specific tools",
        "platforms": {"windows": True, "linux": False, "macos": False, "mobile": False},
        "learning_curve": "Medium",
        "python_version": "3.6+",
        "install_difficulty": "Complex",
        "community": "Low",
        "performance": "Medium",
        "documentation": "Basic",
        "category": "Legacy / Specialized Mockups",
        "github_stars": "1k+",
        "last_update": "2024"
    },
    "Libavg": {
        "tech": "Multimedia",
        "license": "LGPL",
        "use_case": "Multimedia, Graphics",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Hard",
        "python_version": "3.6+",
        "install_difficulty": "Complex",
        "community": "Low",
        "performance": "High",
        "documentation": "Basic",
        "category": "Legacy / Specialized Mockups",
        "github_stars": "200+",
        "last_update": "2024"
    },
    "Streamlit": {
        "tech": "Web/React",
        "license": "Apache 2",
        "use_case": "Data Science Dashboards",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Easy",
        "python_version": "3.7+",
        "install_difficulty": "Easy",
        "community": "High",
        "performance": "Medium",
        "documentation": "Excellent",
        "category": "Web-Based",
        "github_stars": "65k+",
        "last_update": "2024"
    },
    "Gradio": {
        "tech": "Web/FastAPI",
        "license": "Apache 2",
        "use_case": "ML/AI Interfaces",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Easy",
        "python_version": "3.8+",
        "install_difficulty": "Easy",
        "community": "High",
        "performance": "Medium",
        "documentation": "Good",
        "category": "Web-Based",
        "github_stars": "25k+",
        "last_update": "2024"
    },
    "Textual": {
        "tech": "Terminal/Rich",
        "license": "MIT",
        "use_case": "Terminal Applications",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Medium",
        "python_version": "3.8+",
        "install_difficulty": "Easy",
        "community": "Medium",
        "performance": "High",
        "documentation": "Good",
        "category": "Terminal UI",
        "github_stars": "25k+",
        "last_update": "2024"
    },
    "Rich": {
        "tech": "Terminal Library",
        "license": "MIT",
        "use_case": "Terminal Formatting",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": False},
        "learning_curve": "Easy",
        "python_version": "3.6+",
        "install_difficulty": "Easy",
        "community": "High",
        "performance": "High",
        "documentation": "Excellent",
        "category": "Terminal UI",
        "github_stars": "65k+",
        "last_update": "2024"
    },
    "Dash": {
        "tech": "Web/Plotly",
        "license": "MIT",
        "use_case": "Analytical Dashboards",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Medium",
        "python_version": "3.7+",
        "install_difficulty": "Medium",
        "community": "High",
        "performance": "Medium",
        "documentation": "Excellent",
        "category": "Web-Based",
        "github_stars": "20k+",
        "last_update": "2024"
    },
    "Remi": {
        "tech": "Web/Pure Python",
        "license": "Apache 2",
        "use_case": "Lightweight Web GUIs",
        "platforms": {"windows": True, "linux": True, "macos": True, "mobile": True},
        "learning_curve": "Easy",
        "python_version": "3.6+",
        "install_difficulty": "Easy",
        "community": "Medium",
        "performance": "Medium",
        "documentation": "Good",
        "category": "Web-Based",
        "github_stars": "4k+",
        "last_update": "2024"
    }
}

# Feature support matrix
FEATURE_MATRIX = {
    "Standard Tkinter": {
        "native_date_picker": False,
        "native_switch": False,
        "native_table": True,
        "themes_styling": False,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "CustomTkinter": {
        "native_date_picker": False,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "PySide6": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": True
    },
    "PyQt6": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": True
    },
    "wxPython": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": False
    },
    "Kivy": {
        "native_date_picker": False,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": False
    },
    "PySimpleGUI": {
        "native_date_picker": True,
        "native_switch": False,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "Dear PyGui": {
        "native_date_picker": True,
        "native_switch": False,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "Flet": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": True
    },
    "NiceGUI": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": True
    },
    "PyWebView": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": True
    },
    "Eel": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": True
    },
    "Flexx": {
        "native_date_picker": False,
        "native_switch": False,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": True
    },
    "Gooey": {
        "native_date_picker": True,
        "native_switch": False,
        "native_table": False,
        "themes_styling": False,
        "custom_widgets": False,
        "drag_drop": False,
        "multithreading": False,
        "web_integration": False
    },
    "Toga": {
        "native_date_picker": False,
        "native_switch": True,
        "native_table": True,
        "themes_styling": False,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "appJar": {
        "native_date_picker": True,
        "native_switch": False,
        "native_table": True,
        "themes_styling": False,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "PyGUI": {
        "native_date_picker": False,
        "native_switch": False,
        "native_table": False,
        "themes_styling": False,
        "custom_widgets": False,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "PyForms": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": True,
        "multithreading": True,
        "web_integration": False
    },
    "Libavg": {
        "native_date_picker": False,
        "native_switch": False,
        "native_table": False,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "Streamlit": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": True
    },
    "Gradio": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": True
    },
    "Textual": {
        "native_date_picker": False,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "Rich": {
        "native_date_picker": False,
        "native_switch": False,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": False
    },
    "Dash": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": True
    },
    "Remi": {
        "native_date_picker": True,
        "native_switch": True,
        "native_table": True,
        "themes_styling": True,
        "custom_widgets": True,
        "drag_drop": False,
        "multithreading": True,
        "web_integration": True
    }
}

# Feature labels for display
FEATURE_LABELS = {
    "native_date_picker": "Native Date Picker",
    "native_switch": "Native Switch/Toggle",
    "native_table": "Native Table/Grid",
    "themes_styling": "Themes/Styling",
    "custom_widgets": "Custom Widgets",
    "drag_drop": "Drag & Drop",
    "multithreading": "Multithreading",
    "web_integration": "Web Integration"
}
